[package]
name = "shell-quote"
version = "0.1.0"
authors = ["Gavin Panella <gavinpanella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
