name: shell-quote CI

on:
  push:
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      # Make sure we have all the target shells installed.
      - run: sudo apt-get install -y bash dash fish zsh
      - run: bash --version
      - run: dash -c env # dash doesn't have a `--version` flag.
      - run: fish --version
      - run: zsh --version
      # Test in debug mode first.
      - run: cargo test
      # Test in release mode too, to defend against, for example, use of
      # `debug_assert!` with side effects, i.e. those side effects won't happen
      # when compiled with `--release`.
      - run: cargo test --release

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy # i.e. `cargo check` plus extra linting.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-targets -- -D warnings
